default: &default
  adapter: mysql2  
  encoding: utf8  
  pool: 5
  timeout: 5000  
  username: 
  password: 

development:
  <<: *default
  database: tool_three_dev

test:
  <<: *default
  database: tool_three_test
